Controllers/ActorController.cs
using System.Collections.Generic;
using System.Linq;
using New_with_Views.Models;
using New_with_Views.Models.Repositories;
using Microsoft.AspNetCore.Mvc;
using New_with_Views.Models.Entities;
using New_with_Views.Models.ViewModels;

namespace New_with_Views.Controllers
{
    public class ActorController : Controller
    {
        // Loosly Coupled
        private IActorRepository _actorRepository;
        private IMovieRepository _movieRepository;

        public ActorController(IActorRepository actorRepository, IMovieRepository movieRepository)
        {
            this._actorRepository = actorRepository;
            this._movieRepository = movieRepository;
        }

        // Read
        [HttpGet]
        public IActionResult Index()
        {
            IEnumerable<Actor> actors = _actorRepository.GetAll();
            return View(actors);
            
        }

        // Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        //Create
        [HttpPost]
        public IActionResult Create(Actor ac)
        {
            if (ModelState.IsValid)
            {
                _actorRepository.Save(ac);
                return RedirectToAction("Index");

            }
            else
            {
                return View();
            }
        }

        // Update
        public IActionResult Update(int id)
        {
            Actor actor =  _actorRepository.Get(id);
            
            return View(actor);
        }
        [HttpPost]
        public IActionResult Update(Actor actor)
        {
            if (ModelState.IsValid)
            {
                _actorRepository.Update(actor);
                return RedirectToAction("Index");
            }
            return View(actor);
        }

        //Delete
        [HttpGet]
        public IActionResult Delete(int id)
        {
            Actor actor =  _actorRepository.Get(id);
            return View(actor);
        }

        [HttpPost]
        public IActionResult Delete(Actor ac)
        {
            _actorRepository.Delete(ac);
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            var actor = _actorRepository.Get(id);
            return View(actor);
        }
    }
}

Controllers/MovieController.cs
using System.Collections.Generic;
using System.Linq;
using New_with_Views.Models;
using New_with_Views.Models.Repositories;
using Microsoft.AspNetCore.Mvc;
using New_with_Views.Models.Entities;
using New_with_Views.Models.ViewModels;
using System;

namespace New_with_Views.Controllers
{
    public class MovieController : Controller
    {
        // Loosly Coupled
        private IMovieRepository _movieRepository;
        private IActorRepository _actorRepository;

        public MovieController(IMovieRepository movieRepository, IActorRepository actorRepository)
        {
            this._movieRepository = movieRepository;
            this._actorRepository = actorRepository;
            
        }

        // Read
        [HttpGet]
        public IActionResult Index(string searchString)
        {
            /*IEnumerable<Movie> movies = _movieRepository.GetAll();
            return View(movies);*/
            
            var movies = from m in _movieRepository.GetAll() 
                 select m;

            if (!string.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(m => m.MovieTitle.Contains(searchString));
            }

            return View(movies);

        }

        // Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        //Create
        [HttpPost]
        public IActionResult Create(Movie mo)
        {
            if (ModelState.IsValid)
            {
                _movieRepository.Save(mo);
                return RedirectToAction("Index");

            }
            else
            {
                return View();
            }
        }

        // Update
        public IActionResult Update(int id)
        {
            Movie movie =  _movieRepository.Get(id);
            return View(movie);
        }
        [HttpPost]
        public IActionResult Update(Movie movie)
        {
            if (ModelState.IsValid)
            {
                _movieRepository.Update(movie);
                return RedirectToAction("Index");
            }
            return View(movie);
        }

        //Delete
        [HttpGet]
        public IActionResult Delete(int id)
        {
            Movie movie =  _movieRepository.Get(id);
            return View(movie);
        }

        [HttpPost]
        public IActionResult Delete(Movie mo)
        {
            _movieRepository.Delete(mo);
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            var movie = _movieRepository.Get(id);
            return View(movie);
        }

        public IActionResult InMovie(int id){
            MovieActorViewModel mavm = new MovieActorViewModel();
            mavm.Movie = _movieRepository.Get(id);
            mavm.Actors = _actorRepository.GetAll();

            return View(mavm);
        }
        /*public IActionResult Search(string searchString)
        {
        }*/

    }
}

Views/Shared/_Layout.cshtml
<!-- Shared View / Layout Page -->
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Movie</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">
    <!--link rel="stylesheet" href="../css/style.css" -->
</head>

<body class="container" style="padding-top: 70px;">
    <nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
        <div class="container-fluid">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-controller="Movie" asp-action="Index">Movies</a></li>
                    <li><a asp-controller="Movie" asp-action="Create">Create New Movie</a></li>
                    <li><a asp-controller="Actor" asp-action="Index">Actors</a></li>
                    <li><a asp-controller="Actor" asp-action="Create">Create New Actor</a></li>
                </ul>
                <form class="navbar-form navbar-right" >
                    <div class="form-group">
                       
                            @using (Html.BeginForm())
                            {
                                <div class="form-control" style="background-color:#222222; border:none;">Search &nbsp &nbsp @Html.TextBox("SearchString")</div><input type="Submit" class="btn btn-info" value="Filter">
                            }
                </form>
            </div>
        </div>
    </nav>
    <div class="jumbotron" style="background-color: gray; text-align: center;">
        <h1>@ViewBag.Title</h1>
        <h3>@ViewBag.Phrase</h3>
    </div>

        @RenderBody()

    <address class="navbar-fixed-bottom">
        &copy; RHansen
    </address>

</body>

</html>